powerUsage <- read.csv("2DayData.csv",sep=" ")
powerUsage$DT <- as.POSIXct(paste(powerUsage$Date, powerUsage$Time), format="%Y-%m-%d %H:%M:%S")
sm1 <- as.character(powerUsage$Sub_metering_1)
sm1_numeric <- as.numeric(sm1)
sm2 <- as.character(powerUsage$Sub_metering_2)
sm2_numeric <- as.numeric(sm2)
sm3 <- as.character(powerUsage$Sub_metering_3)
sm3_numeric <- as.numeric(sm3)
png(filename = "plot3.png",width = 480, height = 480, units = "px", pointsize = 12)
plot(sm1_numeric ~ powerUsage$DT,col="black",ylab="Energy sub metering",type="l",xlab="")
lines(sm2_numeric ~ powerUsage$DT,col="red")
lines(sm3_numeric ~ powerUsage$DT,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("sub metering 1","sub metering 2","sub metering 3"),cex = 1, lwd = 3)
dev.off()